# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: 
    - master 
    - preview 
    - reviewing

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/master' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd /home/ubuntu
          [ ! -d DBRDoc ] && mkdir -p DBRDoc
          cd barcode-reader-docs && git pull && cd .. && cp -rfp ./barcode-reader-docs/* ./DBRDoc/
          cd barcode-reader-docs-js && git pull && cd .. && cp -rfp ./barcode-reader-docs-js/* ./DBRDoc/
          cd barcode-reader-docs-mobile && git pull && cd .. && cp -rfp ./barcode-reader-docs-mobile/* ./DBRDoc/
          cd Docs-Template-Repo && git pull && cd .. && cp -rfp ./Docs-Template-Repo/* ./DBRDoc/
          cd DBRDoc && bundle exec jekyll build --incremental
          python3 /home/ubuntu/ftp.py /home/ubuntu/DBRDoc/_site/ ./www.dynamsoft.com/barcode-reader/ prod

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d barcode-reader-docs-preview ] && git clone --depth 1 --branch preview https://github.com/Dynamsoft/barcode-reader-docs.git barcode-reader-docs-preview
          [ ! -d barcode-reader-docs-js-preview ] && git clone --depth 1 --branch preview https://github.com/Dynamsoft/barcode-reader-docs-js.git barcode-reader-docs-js-preview
          [ ! -d barcode-reader-docs-mobile-preview ] && git clone --depth 1 --branch preview https://github.com/Dynamsoft/barcode-reader-docs-mobile.git barcode-reader-docs-mobile-preview
          [ ! -d DBRDocPreview ] && mkdir -p DBRDocPreview
          cd barcode-reader-docs-preview && git pull && cd .. && cp -rfp ./barcode-reader-docs-preview/* ./DBRDocPreview/
          cd barcode-reader-docs-js-preview && git pull && cd .. && cp -rfp ./barcode-reader-docs-js-preview/* ./DBRDocPreview/
          cd barcode-reader-docs-mobile-preview && git pull && cd .. && cp -rfp ./barcode-reader-docs-mobile-preview/* ./DBRDocPreview/
          cd Docs-Template-Repo && git pull && cd .. && cp -rfp ./Docs-Template-Repo/* ./DBRDocPreview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DBRDocPreview/_config.yml
          cd DBRDocPreview && bundle exec jekyll build --incremental

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DBRDocPreview/_site/
          server-dir: /www.dynamsoft.com/barcode-reader/          
          

  Build-Review:
    if: ${{ github.ref == 'refs/heads/reviewing' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DBRDocRestructured ] && rm -rf DBRDocRestructured
          [ -d barcode-reader-docs-reviewing ] && rm -rf barcode-reader-docs-reviewing 
          [ -d DBRDocRestructuredJS ] && rm -rf DBRDocRestructuredJS 
          [ -d barcode-reader-docs-js-reviewing ] && rm -rf barcode-reader-docs-js-reviewing
          [ -d DBRDocRestructuredMobile ] && rm -rf DBRDocRestructuredMobile 
          [ -d barcode-reader-docs-mobile-reviewing ] && rm -rf barcode-reader-docs-mobile-reviewing
          [ -d DBRDocRestructuredServer ] && rm -rf DBRDocRestructuredServer 
          [ -d barcode-reader-docs-server-reviewing ] && rm -rf barcode-reader-docs-server-reviewing
          [ -d Docs-Template-Repo-preview ] && rm -rf Docs-Template-Repo-preview
          cd /home/ubuntu

      - name: Build the site
        run: |
          cd /home/ubuntu
          mkdir -p DBRDocRestructured
          mkdir -p DBRDocRestructuredJS
          mkdir -p DBRDocRestructuredMobile
          mkdir -p DBRDocRestructuredServer
          [ ! -d barcode-reader-docs-reviewing ] && git clone --depth 1 --branch reviewing https://github.com/dynamsoft-docs/barcode-reader-docs.git barcode-reader-docs-reviewing
          [ ! -d barcode-reader-docs-js-reviewing ] && git clone --depth 1 --branch reviewing https://github.com/dynamsoft-docs/barcode-reader-docs-js.git barcode-reader-docs-js-reviewing
          [ ! -d barcode-reader-docs-mobile-reviewing ] && git clone --depth 1 --branch reviewing https://github.com/dynamsoft-docs/barcode-reader-docs-mobile.git barcode-reader-docs-mobile-reviewing
          [ ! -d barcode-reader-docs-server-reviewing ] && git clone --depth 1 --branch reviewing https://github.com/dynamsoft-docs/barcode-reader-docs-server.git barcode-reader-docs-server-reviewing
          [ ! -d Docs-Template-Repo-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-preview
          cd barcode-reader-docs-reviewing && git pull && cd .. && cp -rfp ./barcode-reader-docs-reviewing/* ./DBRDocRestructured/
          cd barcode-reader-docs-js-reviewing && git pull && cd .. && cp -rfp ./barcode-reader-docs-js-reviewing/* ./DBRDocRestructuredJS/
          cd barcode-reader-docs-mobile-reviewing && git pull && cd .. && cp -rfp ./barcode-reader-docs-mobile-reviewing/* ./DBRDocRestructuredMobile/
          cd barcode-reader-docs-server-reviewing && git pull && cd .. && cp -rfp ./barcode-reader-docs-server-reviewing/* ./DBRDocRestructuredServer/
          cd Docs-Template-Repo-preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-preview/* ./DBRDocRestructured/
          cd Docs-Template-Repo-preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-preview/* ./DBRDocRestructuredJS/
          cd Docs-Template-Repo-preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-preview/* ./DBRDocRestructuredMobile/
          cd Docs-Template-Repo-preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-preview/* ./DBRDocRestructuredServer/
          sed -i -e "1,3s/blob\/master$/blob\/reviewing/" \
          -e "1,3s/blob\/main$/blob\/reviewing/" /home/ubuntu/DBRDocRestructured/_config.yml
          sed -i -e "1,3s/blob\/master$/blob\/reviewing/" \
          -e "1,3s/blob\/main$/blob\/reviewing/" /home/ubuntu/DBRDocRestructuredJS/_config.yml
          sed -i -e "1,3s/blob\/master$/blob\/reviewing/" \
          -e "1,3s/blob\/main$/blob\/reviewing/" /home/ubuntu/DBRDocRestructuredMobile/_config.yml
          sed -i -e "1,3s/blob\/master$/blob\/reviewing/" \
          -e "1,3s/blob\/main$/blob\/reviewing/" /home/ubuntu/DBRDocRestructuredServer/_config.yml
          cd DBRDocRestructured && bundle exec jekyll build --incremental && cd ..
          cd DBRDocRestructuredMobile && bundle exec jekyll build --incremental && cd ..
          cd DBRDocRestructuredJS && bundle exec jekyll build --incremental && cd ..
          cd DBRDocRestructuredServer && bundle exec jekyll build --incremental && cd ..

          mkdir -p ./DBRDocRestructured/_site/mobile/
          mkdir -p ./DBRDocRestructured/_site/server/
          mkdir -p ./DBRDocRestructured/_site/web/
          mv ./DBRDocRestructuredJS/_site/* ./DBRDocRestructured/_site/web/
          mv ./DBRDocRestructuredMobile/_site/* ./DBRDocRestructured/_site/mobile/
          mv ./DBRDocRestructuredServer/_site/* ./DBRDocRestructured/_site/server/

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DBRDocRestructured/_site/
          server-dir: /www.dynamsoft.com/barcode-reader-review/docs/
          